const types = {
  ACTIVITY_UPDATE: 'ACTIVITY_UPDATE',
  ANNOTATIONS_CREATE: 'ANNOTATIONS_CREATE',
  ANNOTATIONS_DELETE: 'ANNOTATIONS_DELETE',
  ANNOTATIONS_RESET: 'ANNOTATIONS_RESET',
  ANNOTATIONS_UPDATE_LAST: 'ANNOTATIONS_UPDATE_LAST',
  INITIALIZE: 'INITIALIZE',
  MODE_UPDATE: 'MODE_UPDATE',
  ZOOM_UPDATE: 'ZOOM_UPDATE',
};

export default types;
