export const MODE_UPDATE = 'MODE_UPDATE';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export const ANNOTATIONS_CREATE = 'ANNOTATIONS_CREATE';
export const ANNOTATIONS_UPDATE_LAST = 'ANNOTATIONS_UPDATE_LAST';
export const ANNOTATIONS_RESET = 'ANNOTATIONS_RESET';
export const ZOOM_UPDATE = 'ZOOM_UPDATE';
export const VIEWPORT_UPDATE ='VIEWPORT_UPDATE';
export const SELECTION_UPDATE = 'SELECTION_UPDATE';
export const DELETE_UPDATE = 'DELETE_UPDATE';
export const INITIALIZE = 'INITIALIZE';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const ANNOTATION_DELETE = 'ANNOTATION_DELETE';


